version: 1
formatters:
  simple:
    format: "%(asctime)s %(name)-20s %(levelname)-6s - %(message)s"
    datefmt: "%d/%m/%Y %H:%M:%S"

handlers:
  file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: simple
    filename: logs/frontend.log
    when: midnight
    encoding: utf8
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout

root:
  level: INFO
  handlers: [file, console]
