[server]
port = 8000

[theme]
textColor="#1a1a1a"
font="Calibri"

primaryColor="#1963a0"
backgroundColor="#90C090"
secondaryBackgroundColor="#ffffff"

redTextColor="#8b0303"
redBackgroundColor="#ff5f5f"
greenTextColor="#016806"
greenBackgroundColor="#9cd1b7"
yellowTextColor="#bd7f0c"
yellowBackgroundColor="#f7bd53"


dataframeBorderColor="#976a09"
dataframeHeaderBackgroundColor="#eea73d"
